import Texture from '../prime/texture'
import Sound from '../prime/sound'

export default {
    christmas_man_sprite: new Texture('res/textures/christmas_man_sprite.png', 3, 5, 180, 200),
    loading_bg: new Texture('res/textures/loading_bg.png'),
    schedule: new Texture('res/textures/schedule.png', 1, 1),
    bgm2: new Sound('res/sounds/bgm2.mp3'),
    bgm3: new Sound('res/sounds/bgm3.mp3'),
    count_down_sound: new Sound('res/sounds/count_down.mp3'),
    jump_sound: new Sound('res/sounds/jump.mp3'),
    scream_sound: new Sound('res/sounds/scream.mp3'),
    bingo_sound: new Sound('res/sounds/bingo.mp3'),
    play: new Texture('res/textures/play.png', 1, 1),
    mute: new Texture('res/textures/mute.png', 1, 1),
    moon: new Texture('res/textures/moon.png', 1, 1),
    man: new Texture('res/textures/man.png', 1, 3, 400, 522),
    snow: new Texture('res/textures/snow.png', 1, 1, 50, 50),
    num_1: new Texture('res/textures/number_1.png', 1, 1),
    num_2: new Texture('res/textures/number_2.png', 1, 1),
    num_3: new Texture('res/textures/number_3.png', 1, 1),
    go: new Texture('res/textures/go.png', 1, 1),
    bg: new Texture('res/textures/bg.png', 1, 1),
    tree1: new Texture('res/textures/tree1.png', 1, 1),
    tree2: new Texture('res/textures/tree2.png', 1, 1),
    house1: new Texture('res/textures/house1.png', 1, 1),
    house2: new Texture('res/textures/house2.png', 1, 1),
    house3: new Texture('res/textures/house3.png', 1, 1),
    house4: new Texture('res/textures/house4.png', 1, 1),
    house5: new Texture('res/textures/house5.png', 1, 1),
    house6: new Texture('res/textures/house6.png', 1, 1),
    house7: new Texture('res/textures/house7.png', 1, 1),
    house8: new Texture('res/textures/house8.png', 1, 1),
    score_board: new Texture('res/textures/score_board.png', 1, 1),
    flag: new Texture('res/textures/flag.png', 1, 1),
    primary_bg: new Texture('res/textures/primary_bg.png', 1, 1),
    didi_logo: new Texture('res/textures/didi_logo.png', 1, 1),
    christmas_man: new Texture('res/textures/christmas_man.png', 1, 1),
    primary_title: new Texture('res/textures/primary_title.png', 1, 1),
    help_btn: new Texture('res/textures/help_btn.png', 1, 1),
    again_btn: new Texture('res/textures/again_btn.png', 1, 1),
    share_left: new Texture('res/textures/share_left.png', 1, 1),
    share_right: new Texture('res/textures/share_right.png', 1, 1),
    medium_bg: new Texture('res/textures/primary_bg.png', 1, 1),
    medium_title: new Texture('res/textures/medium_title.png', 1, 1),
    coupon_btn: new Texture('res/textures/coupon_btn.png', 1, 1),
    invite_btn: new Texture('res/textures/invite_btn.png', 1, 1),
    super_bg: new Texture('res/textures/super_bg.png', 1, 1),
    super_title: new Texture('res/textures/super_title.png', 1, 1),
    gift_btn: new Texture('res/textures/gift_btn.png', 1, 1)
}